sudo: required

branches:
  except:
    - gh-pages

env:
  - book="book" stylename="SR54"

before_install:
  - git clone https://github.com/wiztigers/docgen.git docgen
  - chmod +x docgen/setup.sh docgen/docgen.py
  - ./docgen/setup.sh sass ${stylename}

script:
  - ./docgen/docgen.py -v --html --input i18n/en/${book}.adoc  --output index.html --outdir gh-pages/en --stylename ${stylename} --stylesdir sass --linkstyle
  - ./docgen/docgen.py -v --html --input i18n/fr/${book}.adoc  --output index.html --outdir gh-pages/fr --stylename ${stylename} --stylesdir sass --linkstyle
  - ./docgen/docgen.py -v --pdf  --input gh-pages/en/index.html --output ${book}.pdf   --outdir gh-pages/en
  - ./docgen/docgen.py -v --pdf  --input gh-pages/fr/index.html --output ${book}.pdf   --outdir gh-pages/fr
  - cp -r www/* gh-pages

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  committer-from-gh: true
  local-dir: gh-pages
  on:
    branch: master
