sudo: required

before_install:
  - git clone https://github.com/wiztigers/docgen.git docgen
  - chmod +x docgen/setup.sh docgen/docgen.py
  - ./docgen/setup.sh sass

script:
  - ./docgen/docgen.py --html --input book.adoc  --output index.html --outdir gh-pages --stylesheet SR54 --stylesdir sass --linkstyle
  - ./docgen/docgen.py --pdf  --input index.html --output book.pdf   --outdir gh-pages

# https://docs.travis-ci.com/user/deployment/pages/
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  commiter-from-gh: true
  local-dir: gh-pages
  on:
    branch: master

