sudo: required

env:
  - book="book" stylename="SR54"

before_install:
  - git clone https://github.com/wiztigers/docgen.git docgen
  - chmod +x docgen/setup.sh docgen/docgen.py
  - ./docgen/setup.sh sass ${stylename}

script:
  - ./docgen/docgen.py --html --input ${book}.adoc  --output index.html --outdir gh-pages --stylename ${stylename} --stylesdir sass --linkstyle
  - ./docgen/docgen.py --pdf  --input gh-pages/index.html --output ${book}.pdf   --outdir gh-pages
  - AUTHOR_NAME="$(git log -1 $TRAVIS_COMMIT --pretty="%aN")"
  - AUTHOR_EMAIL="$(git log -1 $TRAVIS_COMMIT --pretty="%aE")"
  - cd gh-pages; git config user.name "traviscibot"; git config user.email "deploy@travis-ci.org"
  - git add .; git commit --author="${AUTHOR_NAME} <${AUTHOR_EMAIL}>" -m "Deploy ${TRAVIS_COMMIT_RANGE} to github pages"
  - pwd
  - echo ${AUTHOR_NAME} ${AUTHOR_EMAIL}
  - echo ${TRAVIS_REPO_SLUG}
  - git push --quiet "https://${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}" gh-pages > /dev/null 2>&1
  - cd ..
